rules:
  completeness:
    check_missing_values:
      - column: id
        allowed_null_percentage: 0
      - column: name
        allowed_null_percentage: 0
  accuracy:
    check_format:
      - column: email
        regex: ^[\w\.-]+@[\w\.-]+\.\w+$
      - column: phone_number
        regex: ^(0|84)[0-9]{9}$
    check_range:
      - column: age
        min: 18
        max: 100
    check_allowed_values: []
  consistency:
    check_logic:
      - rule_name: check_start_date_end_after_start
        condition: end_date > start_date
      - rule_name: check_end_date_end_after_start
        condition: end_date > start_date
